### ISSUE TITLE
feat: Support authn request signing

### ISSUE THREAD

**Issue by llamaha** [omniauth/omniauth-saml#141]
Signing is a feature included in the ruby-saml gem:
https://github.com/onelogin/ruby-saml#signing

Minimum parameters:

```
settings.certificate = "CERTIFICATE TEXT WITH HEAD AND FOOT"
settings.private_key = "PRIVATE KEY TEXT WITH HEAD AND FOOT"
settings.security[:authn_requests_signed]   = true     # Enable or not signature on AuthNRequest
```

All parameters:

```
settings.certificate = "CERTIFICATE TEXT WITH HEAD AND FOOT"
settings.private_key = "PRIVATE KEY TEXT WITH HEAD AND FOOT"
settings.security[:authn_requests_signed]   = true     # Enable or not signature on AuthNRequest
settings.security[:logout_requests_signed]  = true     # Enable or not signature on Logout Request
settings.security[:logout_responses_signed] = true     # Enable or not signature on Logout Response
settings.security[:want_assertions_signed]  = true     # Enable or not the requirement of signed assertion
settings.security[:metadata_signed]         = true     # Enable or not signature on Metadata
settings.security[:digest_method]    = XMLSecurity::Document::SHA1
settings.security[:signature_method] = XMLSecurity::Document::RSA_SHA1
settings.security[:embed_sign] = false
```

**Comment by md5** [comment]
@llamaha Is there something preventing you from using this functionality in `omniauth-saml`? I'm pretty sure this already works. I opened a PR with a spec that demonstrates using this feature: #142

The `certificate` parameter is not actually required for signing requests, but adding it will put it into the SP metadata for easy consumption by IdPs. Also, in my testing it looks like `signature_method` is required, though this is probably because we're starting from a hash for configuration instead of a full `OneLogin::RubySaml::Settings` object, which defaults to `XMLSecurity::Document::RSA_SHA1`. It would probably be nice if the `Settings` object did a deep merge, but it doesn't: https://github.com/onelogin/ruby-saml/blob/884e24f94091b13355ebb5f0a6ec97b0905c3938/lib/onelogin/ruby-saml/settings.rb#L13

**Comment by llamaha** [comment]
We were able to make this work using your spec thanks!
