### ISSUE TITLE
Support `protocol_binding` request attribute

### ISSUE THREAD

**Issue by dblessing** [omniauth/omniauth-saml#144]
Some IdP's apparently require an attribute like `ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"` in the request. This is supported by `ruby-saml`: see https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/settings.rb#L46 and https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb#L106

I think it would be fairly reasonable to add this to `omniauth-saml` in https://github.com/omniauth/omniauth-saml/blob/master/lib/omniauth/strategies/saml.rb (add as an options). My biggest question is whether this should have a default value of `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST` or if it's a simple option that users pass in from configuration. Thoughts?

**Comment by md5** [comment]
@dblessing Did you try passing `protocol_binding` as an option? I'm pretty sure the `option` declaration is not required in order to use this setting. The `option` declarations are mainly used for things `omniauth-saml` itself uses directly or for things where we want to change the default.

Since we haven't had a bunch of error reports about this, I think that having the default remain `nil` as it is in `ruby-saml` is fine, which means we don't need to declare the `option`.

**Comment by dblessing** [comment]
Thanks for the idea @md5. We'll give that a try and report back if it doesn't work.
