### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by supernova32** [omniauth/omniauth-saml#88]
With updated dependencies to fix security issues, we need to release 1.5.1

- [ ] Update version.rb
- [ ] Update Gemfile
- [ ] Update CHANGELOG
- [ ] Tag new version
- [ ] Add to releases
- [ ] Build gem
- [ ] Publish gem

**Comment by md5** [comment]
There were no runtime dependencies affected, so I'd probably wait on a
release.

**Comment by supernova32** [comment]
hmm... you are correct. I don't know why I thought that was the case :stuck_out_tongue:

**Comment by bufferoverflow** [comment]
I like this checklist, shall we add that to a ``DEPLOY.md`` or ``RELEASE.md`` or automate this via travis?

**Comment by bufferoverflow** [comment]
or/and start working with the https://github.com/omniauth/omniauth-saml/milestones

**Comment by supernova32** [comment]
@bufferoverflow I like the idea of a `RELEASE.md` containing the checklist. I didn't know Travis could automate this. Is that true?

**Comment by bufferoverflow** [comment]
https://docs.travis-ci.com/user/deployment/rubygems

**Comment by md5** [comment]
It depends on what parts it's automating. Automating the build and push to Rubygems seems OK to me. Perhaps even adding to releases on GitHub. The first four steps seem harder to automate and scare me a bit since Travis could then push commits to the project (which means that a PR could potentially abuse that access if we didn't code `.travis.yml` or any helper scripts in a secure fashion).
