### ISSUE TITLE
Upgrade ruby-saml?

### ISSUE THREAD

**Issue by supernova32** [omniauth/omniauth-saml#96]
`ruby-saml` has been updated to [1.2.0](https://github.com/onelogin/ruby-saml/blob/master/changelog.md#120-april-29-2016). Should we update our dependency?

**Comment by md5** [comment]
I personally don't see any need to update the dependency unless there are required changes in functionality, but I'm not strongly opposed either.

**Comment by bufferoverflow** [comment]
:+1:  for upgrade

**Comment by ilikepi** [comment]
This is a rather rambling comment from someone (me) with relatively little stake in the matter, so apply the appropriate quantity of salt...


It seems to me that it would helpful to test omniauth-saml with ruby-saml 1.2.0 to make sure nothing has broken.  Doing so would not in and of itself require a release to be cut, however.

I have only a rather broad understanding of semver, but if ruby-saml were hypothetically following semver as well, wouldn't omni-auth need to make an in-kind minor release in order to up its dependency requirement?  In other words, ruby-saml went from 1.1.x to 1.2.x, indicating added functionality without breaking changes, so wouldn't omniauth-saml need to go from 1.5.x to 1.6.x for the same reason even if it were solely to update its dependency requirement?

Assuming for a moment the answer to the above is "yes", it seems like bumping the dependency alone is not a sufficient reason to cut a new release.  If a user of omniauth-saml is encountering problems related to something in ruby-saml that was solved in 1.2.0, they could opt to update ruby-saml themselves by hard-coding a dependency for it in their own application.  I've done this numerous times in my own applications.  To me, it seems like this argument would be equally applicable even if omniauth-saml would not need to bump from 1.5.x to 1.6.x.

It feels to me that bumping the dependency is a statement (or at least a suggestion) that older versions of ruby-saml are incompatible or unusable in some way, but skimming the changes for 1.2.0, this seems to be questionable.  There are certain scenarios that caused problems, and those were fixed in 1.2.0, but for some non-trivial number of users, `'~> 1.1', '>= 1.1.1'` is sufficient.  Is this statement or suggestion appropriate to make in the case of ruby-saml 1.2.0?

Personally, I'd say no.  But it's a very weak no.

**Comment by bufferoverflow** [comment]
yep, I would say upgrading ruby-saml needs need new minor release and I agree there should be more to add for a new minor release. Nevertheless master branch is not released and create a MR that updates ruby-saml would be ok from my side.

**Comment by pitbulk** [comment]
The ruby-saml 1.3.0 version contains a [security fix](https://github.com/onelogin/ruby-saml/commit/a571f52171e6bfd87db59822d1d9e8c38fb3b995), adding extra validations to prevent Signature wrapping attacks  [CVE-2016-5697](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-5697)

**Comment by md5** [comment]
Thanks @pitbulk. I've opened https://github.com/omniauth/omniauth-saml/pull/103

@omniauth/omniauth-saml-maintainers I recommend we cut a 1.6.0 release with just this change (and #95, which was already merged). There are other open PRs, but I think they should be in a subsequent release.
